apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: springmusic
  name: springmusic
spec:
  replicas: 2
  selector:
    matchLabels:
      run: springmusic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: springmusic
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://ahead-news-postgresql.default.svc.cluster.local:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: VMware1!
        - name: SPRING_PROFILES_ACTIVE
          value: postgres
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        image: mytkrausjr/spring-music:76a3fc4fe5a46036dc929a4d5986e8336543eabd
        imagePullPolicy: Always
        name: springmusic
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
